### ISSUE TITLE
Technical Tutorial

### ISSUE THREAD

**Issue by sheila-huynh** [arlieu/contractor-services-application#2]
**Requirements:**
- Color
- Sound
- Motion
  ○ 1 video was weak
- Audience Relevance
- User engagement-  video, demo
  ○ Demo would have been better as live presentation tan screenshot
- *needs to be really technical
- Don't start off with video/demo
- Put video at 12 to 15 min point when attention starts dying
- Give tutorial
  ALWAYS END with references

**Comment by sheila-huynh** [comment]
[Big Data.pptx](https://github.com/arlieu/contractor-services-application/files/531375/Big.Data.pptx)

**Comment by arlieu** [comment]
Completed Section 2 and added image references.
[Big Data.pptx](https://github.com/arlieu/contractor-services-application/files/531481/Big.Data.pptx)

**Comment by schmidt95** [comment]
Modified my section
[Technical.Tutorial_Big.Data.pptx](https://github.com/arlieu/contractor-services-application/files/537905/Technical.Tutorial_Big.Data.pptx)

**Comment by arlieu** [comment]
Things to do:

- [ ] Slide #'s
- [ ] Update timeline with 2015/16 example
- [ ] Elaborate on service models and deployment
- [ ] Find new NoSQL video
- [ ] Real-world example

**Comment by arlieu** [comment]
[Technical_Tutorial_Big_Data.pptx](https://github.com/arlieu/contractor-services-application/files/543239/Technical_Tutorial_Big_Data.pptx)
I added slide numbers and put a real-world example. @sheila-huynh please update the timeline. @schmidt95 please elaborate on the service models and deployment. The video is not a must, so look around a little, but don't stress too much if we can't find anything.

**Comment by sheila-huynh** [comment]
[Technical_Tutorial_Big_Data.pptx](https://github.com/arlieu/contractor-services-application/files/543444/Technical_Tutorial_Big_Data.pptx)

I added the updated timeline and gave examples of the service models. I didn't elaborate on the service models with text cause the elaboration would be done verbally; therefore I only added pictures. I also reformatted some slides. Final thought, I thought Weaver wanted a real life example with a real life appliance/company? I think the example he gave was Home Depot.

Feel free to disagree or change whatever.

**Comment by sheila-huynh** [comment]
[Technical_Tutorial_Big_Data.pptx](https://github.com/arlieu/contractor-services-application/files/545602/Technical_Tutorial_Big_Data.pptx)

I added the video Robert suggested and added TV logos for Avery's slide. Once you guys look it over and think it's good, I'll submit.

**Comment by arlieu** [comment]
I updated some format issues that I saw. Mainly overlapping text and pictures. Everything seems good though. I'm okay to submit. 
[Technical_Tutorial_Big_Data.pptx](https://github.com/arlieu/contractor-services-application/files/545605/Technical_Tutorial_Big_Data.pptx)
